"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BadgeCheck, ChevronLeft, Eye, LogOut, Search, ShieldCheck, ToggleLeft, ToggleRight, UserPlus, Users } from "lucide-react";
import { supabase } from "@/lib/supabase-browser";

type Creator={id:string;display_name:string;username:string;headline:string|null;avatar_url:string|null;is_active:boolean;is_verified:boolean;created_at:string};
export default function AdminCreators(){
 const[ready,setReady]=useState(false),[authorized,setAuthorized]=useState(false),[creators,setCreators]=useState<Creator[]>([]),[q,setQ]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setReady(true);return;}const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(me?.role!=="SUPER_ADMIN"){setReady(true);return;}setAuthorized(true);const{data}=await supabase.from("profiles").select("id,display_name,username,headline,avatar_url,is_active,is_verified,created_at").eq("role","CREATOR").order("created_at",{ascending:false});setCreators((data||[])as Creator[]);setReady(true);},[]);useEffect(()=>{load();},[load]);
 const filtered=useMemo(()=>creators.filter(c=>[c.display_name,c.username,c.headline].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase())),[creators,q]);
 async function createCreator(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("create");setError("");const form=new FormData(e.currentTarget);const{data:{session}}=await supabase.auth.getSession();const res=await fetch("/api/admin/create-creator",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify(Object.fromEntries(form.entries()))});const body=await res.json();setBusy("");if(!res.ok)setError(body.error||"Unable to create ES account.");else{setMessage("ES account created. The profile owner can now sign in and complete the profile.");e.currentTarget.reset();await load();}}
 async function patch(id:string,payload:Record<string,boolean>){setBusy(id);setError("");const{data:{session}}=await supabase.auth.getSession();const res=await fetch(`/api/admin/creators/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify(payload)});const body=await res.json();setBusy("");if(!res.ok)setError(body.error||"Unable to update ES.");else await load();}
 async function logout(){await supabase.auth.signOut();location.href="/login";}
 if(!ready)return <div className="center-screen"><span className="loader-orb"/></div>;if(!authorized)return <div className="center-screen"><Link className="btn primary" href="/login">Admin login</Link></div>;
 return <main className="dashboard-page-v5 admin-v5"><aside className="dashboard-sidebar-v5"><Link href="/" className="veloura-brand"><span>V</span>VELOURA</Link><div className="workspace-label">Admin</div><nav><Link href="/admin">Home</Link><Link className="active" href="/admin/creators">ES profiles</Link><Link href="/admin/reviews">Reviews</Link><Link href="/admin/visitors">Visitors</Link><Link href="/admin/visitors">Advanced analytics</Link></nav><button className="sidebar-logout" onClick={logout}><LogOut size={17}/> Log out</button></aside><section className="dashboard-content-v5">
 <header className="workspace-header-v5"><div><Link className="back-link-v5" href="/admin"><ChevronLeft size={15}/> Admin home</Link><span className="workspace-kicker"><Users size={14}/> ES MANAGEMENT</span><h1>ES profiles</h1><p>Create User B accounts and control profile visibility without cluttering Admin Home.</p></div></header>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert error">{error}</div>}
 <section className="admin-primary-counts-v5 compact-counts"><article className="admin-count-card-v5 es"><div className="count-icon-v5"><Users/></div><div><span>TOTAL ES</span><h2>{creators.length}</h2><strong>Profiles</strong><p>{creators.filter(c=>c.is_active).length} active</p></div></article><article className="admin-count-card-v5 visitors"><div className="count-icon-v5"><BadgeCheck/></div><div><span>VERIFIED</span><h2>{creators.filter(c=>c.is_verified).length}</h2><strong>Verified profiles</strong><p>{creators.filter(c=>!c.is_verified).length} awaiting verification</p></div></article></section>
 <section className="admin-home-grid-v5 creator-management-grid-v5"><div className="workspace-panel-v5"><div className="panel-head-v5"><div><span className="workspace-kicker">ADD USER TYPE B</span><h2>Create ES account</h2><p>The ES receives CREATOR role and can sign in to complete photos, contact details and media.</p></div><UserPlus/></div><form className="profile-form-v5" onSubmit={createCreator}><div className="two-fields"><label>Display name<input name="display_name" required placeholder="Sienna Vale"/></label><label>Username<input name="username" required pattern="[A-Za-z0-9_.]+" placeholder="sienna"/></label></div><div className="two-fields"><label>Login email<input name="email" type="email" required placeholder="creator@example.com"/></label><label>Temporary password<input name="password" type="password" minLength={8} required placeholder="8+ characters"/></label></div><label>Headline<input name="headline" maxLength={120} placeholder="Independent profile • Private photo journal"/></label><div className="auto-location-note-v6"><span className="live-dot-v6"/><div><strong>Location is automatic</strong><p>The public page shows each visitor&apos;s own approximate city from IP/network data. Admin does not assign an ES location.</p></div></div><button className="btn primary" disabled={busy==="create"}><UserPlus size={16}/>{busy==="create"?"Creating…":"Create ES account"}</button></form></div>
 <div className="workspace-panel-v5"><div className="panel-head-v5"><div><span className="workspace-kicker">DIRECTORY</span><h2>Manage profiles</h2></div></div><div className="admin-search-v5"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name or username…"/></div><div className="admin-es-list-v5">{filtered.map(c=><article key={c.id}><img src={c.avatar_url||"/demo/avatar-v5.svg"} alt=""/><div className="es-list-main"><div><strong>{c.display_name}</strong>{c.is_verified&&<BadgeCheck size={15}/>}</div><span>@{c.username}</span><small>{c.headline||"Profile details not completed yet."}</small></div><div className="es-list-actions"><button className={`status-chip-v5 ${c.is_active?"active":"disabled"}`} disabled={busy===c.id} onClick={()=>patch(c.id,{is_active:!c.is_active})}>{c.is_active?<ToggleRight size={15}/>:<ToggleLeft size={15}/>} {c.is_active?"Active":"Disabled"}</button><button className={`status-chip-v5 ${c.is_verified?"verified":""}`} disabled={busy===c.id} onClick={()=>patch(c.id,{is_verified:!c.is_verified})}><ShieldCheck size={14}/>{c.is_verified?"Verified":"Verify"}</button><Link className="round-icon" href={`/u/${c.username}`}><Eye size={16}/></Link></div></article>)}</div></div></section>
 </section></main>;
}
