"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, LockKeyhole, LogIn, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase-browser";

export default function LoginPage(){const router=useRouter();const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const{data,error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError||!data.user){setError(authError?.message||"Unable to sign in.");setLoading(false);return;}const{data:profile}=await supabase.from("profiles").select("role").eq("id",data.user.id).single();if(profile?.role==="SUPER_ADMIN")router.push("/admin");else if(profile?.role==="CREATOR")router.push("/dashboard");else{setError("Visitor accounts sign in only when a public-profile action requires it.");await supabase.auth.signOut();setLoading(false);return;}router.refresh();}
return <main className="login-page-v5"><section className="login-visual-v5"><Link href="/" className="veloura-brand light"><span>V</span>VELOURA</Link><div><span className="workspace-kicker"><ShieldCheck size={14}/> PRIVATE WORKSPACE</span><h1>One entrance for ES Studio and Admin.</h1><p>Visitors do not use this page. Their sign-in appears only when they write a review or unlock private media from a shared public profile.</p><div className="login-points-v5"><span><LockKeyhole/>ES profile & content management</span><span><ShieldCheck/>Admin moderation & platform controls</span></div></div></section><section className="login-form-side-v5"><div className="login-card-v5"><Link className="back-link-v5" href="/"><ArrowLeft size={15}/> Back</Link><span className="workspace-kicker">WELCOME BACK</span><h2>Sign in</h2><p>Use your Veloura demo ES or Admin account.</p><form className="profile-form-v5" onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>{error&&<div className="alert error">{error}</div>}<button className="btn primary wide" disabled={loading}>{loading?"Signing in…":<><LogIn size={17}/> Sign in</>}</button></form><small className="login-note-v5">Client demo only. Do not use an external service password.</small></div></section></main>}
