"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ChevronLeft, ImagePlus, LogOut, Search, ShieldCheck, Star, Trash2, UserRound, XCircle } from "lucide-react";
import { supabase } from "@/lib/supabase-browser";
import { uploadToCloudinary } from "@/lib/cloudinary-upload";

type Creator={id:string;display_name:string;username:string};
type Review={id:string;creator_id:string;reviewer_name:string;reviewer_first_name:string|null;reviewer_last_name:string|null;reviewer_avatar_url:string|null;rating:number;review_text:string;is_published:boolean;status:"PENDING"|"PUBLISHED"|"REJECTED";source:"VISITOR"|"ADMIN";created_at:string;profiles?:{display_name?:string;username?:string}|null};
export default function AdminReviews(){
 const[ready,setReady]=useState(false),[authorized,setAuthorized]=useState(false),[creators,setCreators]=useState<Creator[]>([]),[reviews,setReviews]=useState<Review[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setReady(true);return;}const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(me?.role!=="SUPER_ADMIN"){setReady(true);return;}setAuthorized(true);const[{data:c},{data:{session}}]=await Promise.all([supabase.from("profiles").select("id,display_name,username").eq("role","CREATOR").order("display_name"),supabase.auth.getSession()]);setCreators((c||[])as Creator[]);if(session?.access_token){const res=await fetch("/api/admin/reviews",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const body=await res.json();if(res.ok)setReviews((body.reviews||[])as Review[]);else setError(body.error||"Unable to load reviews.");}setReady(true);},[]);useEffect(()=>{load();},[load]);
 const filtered=useMemo(()=>reviews.filter(r=>(status==="ALL"||r.status===status)&&[r.reviewer_name,r.review_text,r.profiles?.display_name,r.profiles?.username].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase())),[reviews,q,status]);
 async function addReview(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("create");setError("");const form=new FormData(e.currentTarget);try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Sign in again.");let avatarUrl:null|string=null;const file=form.get("reviewer_avatar")as File;if(file?.size)avatarUrl=(await uploadToCloudinary(file,session.access_token,"review-avatar")).secure_url;const res=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({creator_id:form.get("creator_id"),reviewer_first_name:form.get("reviewer_first_name"),reviewer_last_name:form.get("reviewer_last_name"),rating:Number(form.get("rating")),review_text:form.get("review_text"),reviewer_avatar_url:avatarUrl,publish:form.get("publish")==="on"})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to add review.");setMessage("Review saved successfully.");e.currentTarget.reset();await load();}catch(err){setError(err instanceof Error?err.message:"Unable to add review.");}finally{setBusy("");}}
 async function updateReview(id:string,nextStatus:string){setBusy(id);const{data:{session}}=await supabase.auth.getSession();const res=await fetch(`/api/admin/reviews/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({status:nextStatus})});const body=await res.json();setBusy("");if(!res.ok)setError(body.error||"Unable to update review.");else await load();}
 async function removeReview(id:string){if(!confirm("Delete this review permanently?"))return;setBusy(id);const{data:{session}}=await supabase.auth.getSession();const res=await fetch(`/api/admin/reviews/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${session?.access_token||""}`}});setBusy("");if(res.ok)await load();else setError("Unable to delete review.");}
 async function logout(){await supabase.auth.signOut();location.href="/login";}
 if(!ready)return <div className="center-screen"><span className="loader-orb"/></div>;if(!authorized)return <div className="center-screen"><Link className="btn primary" href="/login">Admin login</Link></div>;
 return <main className="dashboard-page-v5 admin-v5"><aside className="dashboard-sidebar-v5"><Link href="/" className="veloura-brand"><span>V</span>VELOURA</Link><div className="workspace-label">Admin</div><nav><Link href="/admin">Home</Link><Link href="/admin/creators">ES profiles</Link><Link className="active" href="/admin/reviews">Reviews</Link><Link href="/admin/visitors">Visitors</Link><Link href="/admin/visitors">Advanced analytics</Link></nav><button className="sidebar-logout" onClick={logout}><LogOut size={17}/> Log out</button></aside><section className="dashboard-content-v5"><header className="workspace-header-v5"><div><Link className="back-link-v5" href="/admin"><ChevronLeft size={15}/> Admin home</Link><span className="workspace-kicker"><Star size={14}/> REVIEW MANAGEMENT</span><h1>Reviews & reputation</h1><p>Add Admin reviews and moderate Visitor reviews before they become public.</p></div></header>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert error">{error}</div>}
 <section className="admin-home-grid-v5 reviews-admin-grid-v5"><div className="workspace-panel-v5"><div className="panel-head-v5"><div><span className="workspace-kicker">ADD REVIEW</span><h2>Create review for ES</h2><p>First name, last name, optional profile image and 1–5 stars. A default avatar is used when no image is uploaded.</p></div><ImagePlus/></div><form className="profile-form-v5" onSubmit={addReview}><label>ES profile<select name="creator_id" required defaultValue=""><option value="" disabled>Select ES</option>{creators.map(c=><option key={c.id} value={c.id}>{c.display_name} (@{c.username})</option>)}</select></label><div className="two-fields"><label>First name<input name="reviewer_first_name" required placeholder="Daniel"/></label><label>Last name<input name="reviewer_last_name" required placeholder="R."/></label></div><label>Reviewer profile image <small>Optional</small><input name="reviewer_avatar" type="file" accept="image/*"/></label><label>Rating<select name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{"★".repeat(n)} {n} stars</option>)}</select></label><label>Review<textarea name="review_text" minLength={10} maxLength={1200} rows={5} required placeholder="Write a realistic, respectful demo review…"/></label><label className="check-row-v5"><input type="checkbox" name="publish" defaultChecked/> Publish immediately</label><button className="btn primary" disabled={busy==="create"}>{busy==="create"?"Saving…":"Save review"}</button></form></div>
 <div className="workspace-panel-v5 moderation-panel-v5"><div className="panel-head-v5"><div><span className="workspace-kicker">MODERATION</span><h2>{reviews.filter(r=>r.status==="PENDING").length} pending reviews</h2></div></div><div className="review-filterbar-v5"><div className="admin-search-v5"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reviewer, ES or text…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option value="PENDING">Pending</option><option value="PUBLISHED">Published</option><option value="REJECTED">Rejected</option></select></div><div className="moderation-list-v5">{filtered.map(r=><article key={r.id}><img src={r.reviewer_avatar_url||"/demo/reviewers/default-reviewer.svg"} alt=""/><div className="moderation-copy-v5"><div><strong>{r.reviewer_first_name?`${r.reviewer_first_name} ${r.reviewer_last_name||""}`:r.reviewer_name}</strong><span className={`source-chip-v5 ${r.source.toLowerCase()}`}>{r.source}</span><span className={`status-chip-v5 ${r.status.toLowerCase()}`}>{r.status}</span></div><span className="review-stars">{"★".repeat(r.rating)}</span><p>“{r.review_text}”</p><small>{r.profiles?.display_name||"ES"} • {new Date(r.created_at).toLocaleDateString()}</small></div><div className="moderation-actions-v5">{r.status!=="PUBLISHED"&&<button title="Publish" onClick={()=>updateReview(r.id,"PUBLISHED")} disabled={busy===r.id}><ShieldCheck/></button>}{r.status!=="PENDING"&&<button title="Set pending" onClick={()=>updateReview(r.id,"PENDING")} disabled={busy===r.id}><UserRound/></button>}{r.status!=="REJECTED"&&<button title="Reject" onClick={()=>updateReview(r.id,"REJECTED")} disabled={busy===r.id}><XCircle/></button>}<button title="Delete" onClick={()=>removeReview(r.id)} disabled={busy===r.id}><Trash2/></button></div></article>)}{filtered.length===0&&<div className="empty-card-v5">No reviews match this filter.</div>}</div></div></section>
 </section></main>;
}
